name=HaierProtocol
version=0.9.32
author=Pavlo Dudnytskyi <paveldudn@gmail.com>
maintainer=Pavlo Dudnytskyi <paveldudn@gmail.com>
sentence=A library to control Haier smart appliances using serial protocol.
paragraph=Implements Haier transport/protocol framing, message parsing, and request/answer handling for smart appliances.
category=Communication
url=https://github.com/paveldn/HaierProtocol
architectures=*
includes=HaierProtocol.h
license=MIT